export const userConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
};

export const contactConstants = {
  GET_ALL_CONTACTS_REQUEST: "GET_ALL_CONTACTS_REQUEST",
  GET_ALL_CONTACTS_SUCCESS: "GET_ALL_CONTACTS_SUCCESS",
  GET_ALL_CONTACTS_FAILURE: "GET_ALL_CONTACTS_FAILURE",

  ADD_CONTACT_REQUEST: "ADD_CONTACT_REQUEST",
  ADD_CONTACT_SUCCESS: "ADD_CONTACT_REQUEST",
  ADD_CONTACT_FAILURE: "ADD_CONTACT_FAILURE",
};
